// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package org.cny.jwf.im.pb;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ImMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string i = 1;</code>
     */
    boolean hasI();
    /**
     * <code>optional string i = 1;</code>
     */
    java.lang.String getI();
    /**
     * <code>optional string i = 1;</code>
     */
    com.google.protobuf.ByteString
        getIBytes();

    /**
     * <code>optional string s = 2;</code>
     */
    boolean hasS();
    /**
     * <code>optional string s = 2;</code>
     */
    java.lang.String getS();
    /**
     * <code>optional string s = 2;</code>
     */
    com.google.protobuf.ByteString
        getSBytes();

    /**
     * <code>repeated string r = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getRList();
    /**
     * <code>repeated string r = 3;</code>
     */
    int getRCount();
    /**
     * <code>repeated string r = 3;</code>
     */
    java.lang.String getR(int index);
    /**
     * <code>repeated string r = 3;</code>
     */
    com.google.protobuf.ByteString
        getRBytes(int index);

    /**
     * <code>required uint32 t = 4;</code>
     */
    boolean hasT();
    /**
     * <code>required uint32 t = 4;</code>
     */
    int getT();

    /**
     * <code>optional string d = 5;</code>
     */
    boolean hasD();
    /**
     * <code>optional string d = 5;</code>
     */
    java.lang.String getD();
    /**
     * <code>optional string d = 5;</code>
     */
    com.google.protobuf.ByteString
        getDBytes();

    /**
     * <code>required bytes c = 6;</code>
     */
    boolean hasC();
    /**
     * <code>required bytes c = 6;</code>
     */
    com.google.protobuf.ByteString getC();

    /**
     * <code>optional int64 time = 7;</code>
     */
    boolean hasTime();
    /**
     * <code>optional int64 time = 7;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code ImMsg}
   */
  public static final class ImMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ImMsg)
      ImMsgOrBuilder {
    // Use ImMsg.newBuilder() to construct.
    private ImMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ImMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ImMsg defaultInstance;
    public static ImMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ImMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ImMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              i_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                r_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              r_.add(bs);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              t_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              d_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              c_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          r_ = r_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cny.jwf.im.pb.Msg.internal_static_ImMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cny.jwf.im.pb.Msg.internal_static_ImMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cny.jwf.im.pb.Msg.ImMsg.class, org.cny.jwf.im.pb.Msg.ImMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ImMsg> PARSER =
        new com.google.protobuf.AbstractParser<ImMsg>() {
      public ImMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ImMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int I_FIELD_NUMBER = 1;
    private java.lang.Object i_;
    /**
     * <code>optional string i = 1;</code>
     */
    public boolean hasI() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string i = 1;</code>
     */
    public java.lang.String getI() {
      java.lang.Object ref = i_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          i_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string i = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIBytes() {
      java.lang.Object ref = i_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        i_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_FIELD_NUMBER = 2;
    private java.lang.Object s_;
    /**
     * <code>optional string s = 2;</code>
     */
    public boolean hasS() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s = 2;</code>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int R_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList r_;
    /**
     * <code>repeated string r = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRList() {
      return r_;
    }
    /**
     * <code>repeated string r = 3;</code>
     */
    public int getRCount() {
      return r_.size();
    }
    /**
     * <code>repeated string r = 3;</code>
     */
    public java.lang.String getR(int index) {
      return r_.get(index);
    }
    /**
     * <code>repeated string r = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRBytes(int index) {
      return r_.getByteString(index);
    }

    public static final int T_FIELD_NUMBER = 4;
    private int t_;
    /**
     * <code>required uint32 t = 4;</code>
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 t = 4;</code>
     */
    public int getT() {
      return t_;
    }

    public static final int D_FIELD_NUMBER = 5;
    private java.lang.Object d_;
    /**
     * <code>optional string d = 5;</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string d = 5;</code>
     */
    public java.lang.String getD() {
      java.lang.Object ref = d_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          d_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string d = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDBytes() {
      java.lang.Object ref = d_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        d_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString c_;
    /**
     * <code>required bytes c = 6;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes c = 6;</code>
     */
    public com.google.protobuf.ByteString getC() {
      return c_;
    }

    public static final int TIME_FIELD_NUMBER = 7;
    private long time_;
    /**
     * <code>optional int64 time = 7;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 time = 7;</code>
     */
    public long getTime() {
      return time_;
    }

    private void initFields() {
      i_ = "";
      s_ = "";
      r_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      t_ = 0;
      d_ = "";
      c_ = com.google.protobuf.ByteString.EMPTY;
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasT()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSBytes());
      }
      for (int i = 0; i < r_.size(); i++) {
        output.writeBytes(3, r_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, t_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getDBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, c_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(7, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < r_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(r_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getRList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, t_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, c_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.ImMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cny.jwf.im.pb.Msg.ImMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImMsg)
        org.cny.jwf.im.pb.Msg.ImMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cny.jwf.im.pb.Msg.internal_static_ImMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cny.jwf.im.pb.Msg.internal_static_ImMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cny.jwf.im.pb.Msg.ImMsg.class, org.cny.jwf.im.pb.Msg.ImMsg.Builder.class);
      }

      // Construct using org.cny.jwf.im.pb.Msg.ImMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        i_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        s_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        r_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        t_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        d_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        c_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cny.jwf.im.pb.Msg.internal_static_ImMsg_descriptor;
      }

      public org.cny.jwf.im.pb.Msg.ImMsg getDefaultInstanceForType() {
        return org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance();
      }

      public org.cny.jwf.im.pb.Msg.ImMsg build() {
        org.cny.jwf.im.pb.Msg.ImMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cny.jwf.im.pb.Msg.ImMsg buildPartial() {
        org.cny.jwf.im.pb.Msg.ImMsg result = new org.cny.jwf.im.pb.Msg.ImMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.i_ = i_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s_ = s_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          r_ = r_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.r_ = r_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.t_ = t_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cny.jwf.im.pb.Msg.ImMsg) {
          return mergeFrom((org.cny.jwf.im.pb.Msg.ImMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cny.jwf.im.pb.Msg.ImMsg other) {
        if (other == org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance()) return this;
        if (other.hasI()) {
          bitField0_ |= 0x00000001;
          i_ = other.i_;
          onChanged();
        }
        if (other.hasS()) {
          bitField0_ |= 0x00000002;
          s_ = other.s_;
          onChanged();
        }
        if (!other.r_.isEmpty()) {
          if (r_.isEmpty()) {
            r_ = other.r_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRIsMutable();
            r_.addAll(other.r_);
          }
          onChanged();
        }
        if (other.hasT()) {
          setT(other.getT());
        }
        if (other.hasD()) {
          bitField0_ |= 0x00000010;
          d_ = other.d_;
          onChanged();
        }
        if (other.hasC()) {
          setC(other.getC());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasT()) {
          
          return false;
        }
        if (!hasC()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cny.jwf.im.pb.Msg.ImMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cny.jwf.im.pb.Msg.ImMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object i_ = "";
      /**
       * <code>optional string i = 1;</code>
       */
      public boolean hasI() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string i = 1;</code>
       */
      public java.lang.String getI() {
        java.lang.Object ref = i_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            i_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string i = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIBytes() {
        java.lang.Object ref = i_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          i_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string i = 1;</code>
       */
      public Builder setI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        i_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string i = 1;</code>
       */
      public Builder clearI() {
        bitField0_ = (bitField0_ & ~0x00000001);
        i_ = getDefaultInstance().getI();
        onChanged();
        return this;
      }
      /**
       * <code>optional string i = 1;</code>
       */
      public Builder setIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        i_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s_ = "";
      /**
       * <code>optional string s = 2;</code>
       */
      public boolean hasS() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public java.lang.String getS() {
        java.lang.Object ref = s_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        java.lang.Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder setS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder clearS() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 2;</code>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList r_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          r_ = new com.google.protobuf.LazyStringArrayList(r_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRList() {
        return r_.getUnmodifiableView();
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public int getRCount() {
        return r_.size();
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public java.lang.String getR(int index) {
        return r_.get(index);
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRBytes(int index) {
        return r_.getByteString(index);
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public Builder setR(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
        r_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public Builder addR(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
        r_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public Builder addAllR(
          java.lang.Iterable<java.lang.String> values) {
        ensureRIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, r_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public Builder clearR() {
        r_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string r = 3;</code>
       */
      public Builder addRBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
        r_.add(value);
        onChanged();
        return this;
      }

      private int t_ ;
      /**
       * <code>required uint32 t = 4;</code>
       */
      public boolean hasT() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 t = 4;</code>
       */
      public int getT() {
        return t_;
      }
      /**
       * <code>required uint32 t = 4;</code>
       */
      public Builder setT(int value) {
        bitField0_ |= 0x00000008;
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 t = 4;</code>
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000008);
        t_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object d_ = "";
      /**
       * <code>optional string d = 5;</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string d = 5;</code>
       */
      public java.lang.String getD() {
        java.lang.Object ref = d_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            d_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string d = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDBytes() {
        java.lang.Object ref = d_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          d_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string d = 5;</code>
       */
      public Builder setD(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string d = 5;</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000010);
        d_ = getDefaultInstance().getD();
        onChanged();
        return this;
      }
      /**
       * <code>optional string d = 5;</code>
       */
      public Builder setDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        d_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString c_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes c = 6;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes c = 6;</code>
       */
      public com.google.protobuf.ByteString getC() {
        return c_;
      }
      /**
       * <code>required bytes c = 6;</code>
       */
      public Builder setC(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes c = 6;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000020);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 7;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 time = 7;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 7;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000040;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 7;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        time_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ImMsg)
    }

    static {
      defaultInstance = new ImMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ImMsg)
  }

  public interface RCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string r = 1;</code>
     */
    boolean hasR();
    /**
     * <code>required string r = 1;</code>
     */
    java.lang.String getR();
    /**
     * <code>required string r = 1;</code>
     */
    com.google.protobuf.ByteString
        getRBytes();

    /**
     * <code>required string c = 2;</code>
     */
    boolean hasC();
    /**
     * <code>required string c = 2;</code>
     */
    java.lang.String getC();
    /**
     * <code>required string c = 2;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();
  }
  /**
   * Protobuf type {@code RC}
   */
  public static final class RC extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RC)
      RCOrBuilder {
    // Use RC.newBuilder() to construct.
    private RC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RC(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RC defaultInstance;
    public static RC getDefaultInstance() {
      return defaultInstance;
    }

    public RC getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private RC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              r_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              c_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cny.jwf.im.pb.Msg.internal_static_RC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cny.jwf.im.pb.Msg.internal_static_RC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cny.jwf.im.pb.Msg.RC.class, org.cny.jwf.im.pb.Msg.RC.Builder.class);
    }

    public static com.google.protobuf.Parser<RC> PARSER =
        new com.google.protobuf.AbstractParser<RC>() {
      public RC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RC(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RC> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int R_FIELD_NUMBER = 1;
    private java.lang.Object r_;
    /**
     * <code>required string r = 1;</code>
     */
    public boolean hasR() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string r = 1;</code>
     */
    public java.lang.String getR() {
      java.lang.Object ref = r_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          r_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string r = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRBytes() {
      java.lang.Object ref = r_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        r_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C_FIELD_NUMBER = 2;
    private java.lang.Object c_;
    /**
     * <code>required string c = 2;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string c = 2;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      r_ = "";
      c_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasR()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.RC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cny.jwf.im.pb.Msg.RC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RC)
        org.cny.jwf.im.pb.Msg.RCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cny.jwf.im.pb.Msg.internal_static_RC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cny.jwf.im.pb.Msg.internal_static_RC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cny.jwf.im.pb.Msg.RC.class, org.cny.jwf.im.pb.Msg.RC.Builder.class);
      }

      // Construct using org.cny.jwf.im.pb.Msg.RC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        r_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cny.jwf.im.pb.Msg.internal_static_RC_descriptor;
      }

      public org.cny.jwf.im.pb.Msg.RC getDefaultInstanceForType() {
        return org.cny.jwf.im.pb.Msg.RC.getDefaultInstance();
      }

      public org.cny.jwf.im.pb.Msg.RC build() {
        org.cny.jwf.im.pb.Msg.RC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cny.jwf.im.pb.Msg.RC buildPartial() {
        org.cny.jwf.im.pb.Msg.RC result = new org.cny.jwf.im.pb.Msg.RC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.r_ = r_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.c_ = c_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cny.jwf.im.pb.Msg.RC) {
          return mergeFrom((org.cny.jwf.im.pb.Msg.RC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cny.jwf.im.pb.Msg.RC other) {
        if (other == org.cny.jwf.im.pb.Msg.RC.getDefaultInstance()) return this;
        if (other.hasR()) {
          bitField0_ |= 0x00000001;
          r_ = other.r_;
          onChanged();
        }
        if (other.hasC()) {
          bitField0_ |= 0x00000002;
          c_ = other.c_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasR()) {
          
          return false;
        }
        if (!hasC()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cny.jwf.im.pb.Msg.RC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cny.jwf.im.pb.Msg.RC) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object r_ = "";
      /**
       * <code>required string r = 1;</code>
       */
      public boolean hasR() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string r = 1;</code>
       */
      public java.lang.String getR() {
        java.lang.Object ref = r_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            r_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string r = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRBytes() {
        java.lang.Object ref = r_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          r_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string r = 1;</code>
       */
      public Builder setR(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        r_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string r = 1;</code>
       */
      public Builder clearR() {
        bitField0_ = (bitField0_ & ~0x00000001);
        r_ = getDefaultInstance().getR();
        onChanged();
        return this;
      }
      /**
       * <code>required string r = 1;</code>
       */
      public Builder setRBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        r_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object c_ = "";
      /**
       * <code>required string c = 2;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string c = 2;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            c_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c = 2;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 2;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 2;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RC)
    }

    static {
      defaultInstance = new RC(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RC)
  }

  public interface DsMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DsMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ImMsg m = 1;</code>
     */
    boolean hasM();
    /**
     * <code>required .ImMsg m = 1;</code>
     */
    org.cny.jwf.im.pb.Msg.ImMsg getM();
    /**
     * <code>required .ImMsg m = 1;</code>
     */
    org.cny.jwf.im.pb.Msg.ImMsgOrBuilder getMOrBuilder();

    /**
     * <code>repeated .RC rc = 2;</code>
     */
    java.util.List<org.cny.jwf.im.pb.Msg.RC> 
        getRcList();
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    org.cny.jwf.im.pb.Msg.RC getRc(int index);
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    int getRcCount();
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    java.util.List<? extends org.cny.jwf.im.pb.Msg.RCOrBuilder> 
        getRcOrBuilderList();
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    org.cny.jwf.im.pb.Msg.RCOrBuilder getRcOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DsMsg}
   */
  public static final class DsMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DsMsg)
      DsMsgOrBuilder {
    // Use DsMsg.newBuilder() to construct.
    private DsMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DsMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DsMsg defaultInstance;
    public static DsMsg getDefaultInstance() {
      return defaultInstance;
    }

    public DsMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DsMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.cny.jwf.im.pb.Msg.ImMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = m_.toBuilder();
              }
              m_ = input.readMessage(org.cny.jwf.im.pb.Msg.ImMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m_);
                m_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rc_ = new java.util.ArrayList<org.cny.jwf.im.pb.Msg.RC>();
                mutable_bitField0_ |= 0x00000002;
              }
              rc_.add(input.readMessage(org.cny.jwf.im.pb.Msg.RC.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rc_ = java.util.Collections.unmodifiableList(rc_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cny.jwf.im.pb.Msg.internal_static_DsMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cny.jwf.im.pb.Msg.internal_static_DsMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cny.jwf.im.pb.Msg.DsMsg.class, org.cny.jwf.im.pb.Msg.DsMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<DsMsg> PARSER =
        new com.google.protobuf.AbstractParser<DsMsg>() {
      public DsMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DsMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DsMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int M_FIELD_NUMBER = 1;
    private org.cny.jwf.im.pb.Msg.ImMsg m_;
    /**
     * <code>required .ImMsg m = 1;</code>
     */
    public boolean hasM() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ImMsg m = 1;</code>
     */
    public org.cny.jwf.im.pb.Msg.ImMsg getM() {
      return m_;
    }
    /**
     * <code>required .ImMsg m = 1;</code>
     */
    public org.cny.jwf.im.pb.Msg.ImMsgOrBuilder getMOrBuilder() {
      return m_;
    }

    public static final int RC_FIELD_NUMBER = 2;
    private java.util.List<org.cny.jwf.im.pb.Msg.RC> rc_;
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    public java.util.List<org.cny.jwf.im.pb.Msg.RC> getRcList() {
      return rc_;
    }
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    public java.util.List<? extends org.cny.jwf.im.pb.Msg.RCOrBuilder> 
        getRcOrBuilderList() {
      return rc_;
    }
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    public int getRcCount() {
      return rc_.size();
    }
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    public org.cny.jwf.im.pb.Msg.RC getRc(int index) {
      return rc_.get(index);
    }
    /**
     * <code>repeated .RC rc = 2;</code>
     */
    public org.cny.jwf.im.pb.Msg.RCOrBuilder getRcOrBuilder(
        int index) {
      return rc_.get(index);
    }

    private void initFields() {
      m_ = org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance();
      rc_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasM()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getM().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRcCount(); i++) {
        if (!getRc(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, m_);
      }
      for (int i = 0; i < rc_.size(); i++) {
        output.writeMessage(2, rc_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, m_);
      }
      for (int i = 0; i < rc_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rc_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cny.jwf.im.pb.Msg.DsMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cny.jwf.im.pb.Msg.DsMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DsMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DsMsg)
        org.cny.jwf.im.pb.Msg.DsMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cny.jwf.im.pb.Msg.internal_static_DsMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cny.jwf.im.pb.Msg.internal_static_DsMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cny.jwf.im.pb.Msg.DsMsg.class, org.cny.jwf.im.pb.Msg.DsMsg.Builder.class);
      }

      // Construct using org.cny.jwf.im.pb.Msg.DsMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMFieldBuilder();
          getRcFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (mBuilder_ == null) {
          m_ = org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance();
        } else {
          mBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rcBuilder_ == null) {
          rc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rcBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cny.jwf.im.pb.Msg.internal_static_DsMsg_descriptor;
      }

      public org.cny.jwf.im.pb.Msg.DsMsg getDefaultInstanceForType() {
        return org.cny.jwf.im.pb.Msg.DsMsg.getDefaultInstance();
      }

      public org.cny.jwf.im.pb.Msg.DsMsg build() {
        org.cny.jwf.im.pb.Msg.DsMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cny.jwf.im.pb.Msg.DsMsg buildPartial() {
        org.cny.jwf.im.pb.Msg.DsMsg result = new org.cny.jwf.im.pb.Msg.DsMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = mBuilder_.build();
        }
        if (rcBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            rc_ = java.util.Collections.unmodifiableList(rc_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rc_ = rc_;
        } else {
          result.rc_ = rcBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cny.jwf.im.pb.Msg.DsMsg) {
          return mergeFrom((org.cny.jwf.im.pb.Msg.DsMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cny.jwf.im.pb.Msg.DsMsg other) {
        if (other == org.cny.jwf.im.pb.Msg.DsMsg.getDefaultInstance()) return this;
        if (other.hasM()) {
          mergeM(other.getM());
        }
        if (rcBuilder_ == null) {
          if (!other.rc_.isEmpty()) {
            if (rc_.isEmpty()) {
              rc_ = other.rc_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRcIsMutable();
              rc_.addAll(other.rc_);
            }
            onChanged();
          }
        } else {
          if (!other.rc_.isEmpty()) {
            if (rcBuilder_.isEmpty()) {
              rcBuilder_.dispose();
              rcBuilder_ = null;
              rc_ = other.rc_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rcBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRcFieldBuilder() : null;
            } else {
              rcBuilder_.addAllMessages(other.rc_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasM()) {
          
          return false;
        }
        if (!getM().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getRcCount(); i++) {
          if (!getRc(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cny.jwf.im.pb.Msg.DsMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cny.jwf.im.pb.Msg.DsMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.cny.jwf.im.pb.Msg.ImMsg m_ = org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.cny.jwf.im.pb.Msg.ImMsg, org.cny.jwf.im.pb.Msg.ImMsg.Builder, org.cny.jwf.im.pb.Msg.ImMsgOrBuilder> mBuilder_;
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public boolean hasM() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public org.cny.jwf.im.pb.Msg.ImMsg getM() {
        if (mBuilder_ == null) {
          return m_;
        } else {
          return mBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public Builder setM(org.cny.jwf.im.pb.Msg.ImMsg value) {
        if (mBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m_ = value;
          onChanged();
        } else {
          mBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public Builder setM(
          org.cny.jwf.im.pb.Msg.ImMsg.Builder builderForValue) {
        if (mBuilder_ == null) {
          m_ = builderForValue.build();
          onChanged();
        } else {
          mBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public Builder mergeM(org.cny.jwf.im.pb.Msg.ImMsg value) {
        if (mBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              m_ != org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance()) {
            m_ =
              org.cny.jwf.im.pb.Msg.ImMsg.newBuilder(m_).mergeFrom(value).buildPartial();
          } else {
            m_ = value;
          }
          onChanged();
        } else {
          mBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public Builder clearM() {
        if (mBuilder_ == null) {
          m_ = org.cny.jwf.im.pb.Msg.ImMsg.getDefaultInstance();
          onChanged();
        } else {
          mBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public org.cny.jwf.im.pb.Msg.ImMsg.Builder getMBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      public org.cny.jwf.im.pb.Msg.ImMsgOrBuilder getMOrBuilder() {
        if (mBuilder_ != null) {
          return mBuilder_.getMessageOrBuilder();
        } else {
          return m_;
        }
      }
      /**
       * <code>required .ImMsg m = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.cny.jwf.im.pb.Msg.ImMsg, org.cny.jwf.im.pb.Msg.ImMsg.Builder, org.cny.jwf.im.pb.Msg.ImMsgOrBuilder> 
          getMFieldBuilder() {
        if (mBuilder_ == null) {
          mBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.cny.jwf.im.pb.Msg.ImMsg, org.cny.jwf.im.pb.Msg.ImMsg.Builder, org.cny.jwf.im.pb.Msg.ImMsgOrBuilder>(
                  getM(),
                  getParentForChildren(),
                  isClean());
          m_ = null;
        }
        return mBuilder_;
      }

      private java.util.List<org.cny.jwf.im.pb.Msg.RC> rc_ =
        java.util.Collections.emptyList();
      private void ensureRcIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rc_ = new java.util.ArrayList<org.cny.jwf.im.pb.Msg.RC>(rc_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.cny.jwf.im.pb.Msg.RC, org.cny.jwf.im.pb.Msg.RC.Builder, org.cny.jwf.im.pb.Msg.RCOrBuilder> rcBuilder_;

      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public java.util.List<org.cny.jwf.im.pb.Msg.RC> getRcList() {
        if (rcBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rc_);
        } else {
          return rcBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public int getRcCount() {
        if (rcBuilder_ == null) {
          return rc_.size();
        } else {
          return rcBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public org.cny.jwf.im.pb.Msg.RC getRc(int index) {
        if (rcBuilder_ == null) {
          return rc_.get(index);
        } else {
          return rcBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder setRc(
          int index, org.cny.jwf.im.pb.Msg.RC value) {
        if (rcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRcIsMutable();
          rc_.set(index, value);
          onChanged();
        } else {
          rcBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder setRc(
          int index, org.cny.jwf.im.pb.Msg.RC.Builder builderForValue) {
        if (rcBuilder_ == null) {
          ensureRcIsMutable();
          rc_.set(index, builderForValue.build());
          onChanged();
        } else {
          rcBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder addRc(org.cny.jwf.im.pb.Msg.RC value) {
        if (rcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRcIsMutable();
          rc_.add(value);
          onChanged();
        } else {
          rcBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder addRc(
          int index, org.cny.jwf.im.pb.Msg.RC value) {
        if (rcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRcIsMutable();
          rc_.add(index, value);
          onChanged();
        } else {
          rcBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder addRc(
          org.cny.jwf.im.pb.Msg.RC.Builder builderForValue) {
        if (rcBuilder_ == null) {
          ensureRcIsMutable();
          rc_.add(builderForValue.build());
          onChanged();
        } else {
          rcBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder addRc(
          int index, org.cny.jwf.im.pb.Msg.RC.Builder builderForValue) {
        if (rcBuilder_ == null) {
          ensureRcIsMutable();
          rc_.add(index, builderForValue.build());
          onChanged();
        } else {
          rcBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder addAllRc(
          java.lang.Iterable<? extends org.cny.jwf.im.pb.Msg.RC> values) {
        if (rcBuilder_ == null) {
          ensureRcIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rc_);
          onChanged();
        } else {
          rcBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder clearRc() {
        if (rcBuilder_ == null) {
          rc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rcBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public Builder removeRc(int index) {
        if (rcBuilder_ == null) {
          ensureRcIsMutable();
          rc_.remove(index);
          onChanged();
        } else {
          rcBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public org.cny.jwf.im.pb.Msg.RC.Builder getRcBuilder(
          int index) {
        return getRcFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public org.cny.jwf.im.pb.Msg.RCOrBuilder getRcOrBuilder(
          int index) {
        if (rcBuilder_ == null) {
          return rc_.get(index);  } else {
          return rcBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public java.util.List<? extends org.cny.jwf.im.pb.Msg.RCOrBuilder> 
           getRcOrBuilderList() {
        if (rcBuilder_ != null) {
          return rcBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rc_);
        }
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public org.cny.jwf.im.pb.Msg.RC.Builder addRcBuilder() {
        return getRcFieldBuilder().addBuilder(
            org.cny.jwf.im.pb.Msg.RC.getDefaultInstance());
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public org.cny.jwf.im.pb.Msg.RC.Builder addRcBuilder(
          int index) {
        return getRcFieldBuilder().addBuilder(
            index, org.cny.jwf.im.pb.Msg.RC.getDefaultInstance());
      }
      /**
       * <code>repeated .RC rc = 2;</code>
       */
      public java.util.List<org.cny.jwf.im.pb.Msg.RC.Builder> 
           getRcBuilderList() {
        return getRcFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.cny.jwf.im.pb.Msg.RC, org.cny.jwf.im.pb.Msg.RC.Builder, org.cny.jwf.im.pb.Msg.RCOrBuilder> 
          getRcFieldBuilder() {
        if (rcBuilder_ == null) {
          rcBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.cny.jwf.im.pb.Msg.RC, org.cny.jwf.im.pb.Msg.RC.Builder, org.cny.jwf.im.pb.Msg.RCOrBuilder>(
                  rc_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          rc_ = null;
        }
        return rcBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DsMsg)
    }

    static {
      defaultInstance = new DsMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DsMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ImMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DsMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DsMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\"W\n\005ImMsg\022\t\n\001i\030\001 \001(\t\022\t\n\001s\030\002 \001" +
      "(\t\022\t\n\001r\030\003 \003(\t\022\t\n\001t\030\004 \002(\r\022\t\n\001d\030\005 \001(\t\022\t\n\001c" +
      "\030\006 \002(\014\022\014\n\004time\030\007 \001(\003\"\032\n\002RC\022\t\n\001r\030\001 \002(\t\022\t\n" +
      "\001c\030\002 \002(\t\"+\n\005DsMsg\022\021\n\001m\030\001 \002(\0132\006.ImMsg\022\017\n\002" +
      "rc\030\002 \003(\0132\003.RCB\027\n\021org.cny.jwf.im.pbZ\002pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ImMsg_descriptor,
        new java.lang.String[] { "I", "S", "R", "T", "D", "C", "Time", });
    internal_static_RC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RC_descriptor,
        new java.lang.String[] { "R", "C", });
    internal_static_DsMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DsMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DsMsg_descriptor,
        new java.lang.String[] { "M", "Rc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
